server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sample?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: Test@123456
    driverClassName: com.mysql.jdbc.Driver
    max-active: 20
    max-idle: 8
    min-idle: 8
    initial-size: 10

    ########################################################
    ### Java PersistenceApi
    ########################################################
  jpa:
    # Specify the DBMS
    database: MYSQL
    # Show or not log for eachsql query
    show-sql: true
    hibernate:
      #Hibernate ddl auto (create, create-drop, update)
      ddl-auto: update
      # Naming strategy
      #[org.hibernate.cfg.ImprovedNamingStrategy  #org.hibernate.cfg.DefaultNamingStrategy]
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy

#       stripped before adding them to the entity manager)
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect